version: '2'

services:
  backend:
    image: node:6.9.5
    container_name: dpac.backend.dev
    working_dir: "/home"
    entrypoint: ["node_modules/.bin/forever", "app/server.js"]
    environment:
      NODE_ENV: development
    extra_hosts:
      - "mongo:${EN0_IP}"
    ports:
      - "3000:3000"
    volumes:
      - "./app/:/home/app"
      - "./.env/:/home/.env"
      - "./package.json:/home/package.json"
      - "./yarn.lock:/home/yarn.lock"
      - "./node_modules:/home/node_modules"
